"use client";
import { useState } from "react";

const languages = [
  "python", "javascript", "typescript", "java", "go", "rust",
  "cpp", "ruby", "php", "swift", "kotlin", "dart", "sql", "bash",
];

const templates = [
  { id: "nextjs", name: "Next.js App", stack: "React, TypeScript, Tailwind" },
  { id: "fastapi", name: "FastAPI Backend", stack: "Python, SQLAlchemy" },
  { id: "express", name: "Express.js API", stack: "Node.js, TypeScript" },
  { id: "django", name: "Django App", stack: "Python, PostgreSQL" },
  { id: "react_native", name: "React Native", stack: "TypeScript, Expo" },
  { id: "flask", name: "Flask API", stack: "Python, Flask" },
];

export default function CodeStudioPage() {
  const [tab, setTab] = useState<"generate" | "explain" | "project">("generate");
  const [prompt, setPrompt] = useState("");
  const [language, setLanguage] = useState("python");
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    await new Promise((r) => setTimeout(r, 1500));
    const samples: Record<string, string> = {
      python: `# Generated by Ominou Studio AI
# Prompt: ${prompt}

import asyncio
from typing import List

async def process_data(items: List[dict]) -> dict:
    """Process and analyze data items."""
    results = []
    for item in items:
        result = await analyze(item)
        results.append(result)
    return {"processed": len(results), "data": results}

async def analyze(item: dict) -> dict:
    # AI-powered analysis
    return {"id": item.get("id"), "score": 0.95, "status": "complete"}

async def main():
    data = [{"id": i, "value": f"item_{i}"} for i in range(10)]
    output = await process_data(data)
    print(f"Processed {output['processed']} items")

if __name__ == "__main__":
    asyncio.run(main())`,
      javascript: `// Generated by Ominou Studio AI
// Prompt: ${prompt}

const express = require('express');
const app = express();

app.use(express.json());

const items = [];

app.get('/api/items', (req, res) => {
  res.json({ items, count: items.length });
});

app.post('/api/items', (req, res) => {
  const item = { id: Date.now(), ...req.body };
  items.push(item);
  res.status(201).json(item);
});

app.listen(3000, () => console.log('Server running on port 3000'));`,
      typescript: `// Generated by Ominou Studio AI
// Prompt: ${prompt}

interface DataItem {
  id: number;
  value: string;
  score?: number;
}

async function processItems(items: DataItem[]): Promise<DataItem[]> {
  return items.map(item => ({
    ...item,
    score: Math.random() * 100,
  }));
}

const main = async (): Promise<void> => {
  const items: DataItem[] = Array.from({ length: 5 }, (_, i) => ({
    id: i + 1,
    value: \`item_\${i + 1}\`,
  }));

  const processed = await processItems(items);
  console.log(\`Processed \${processed.length} items\`);
};

main();`,
    };
    setResult(samples[language] || samples.python);
    setLoading(false);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 fade-in">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-3">💻 Code Studio</h1>
        <p className="text-surface-500 mt-1">AI code generation, browser IDE, and one-click deployment</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2">
        {(["generate", "explain", "project"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
              tab === t ? "bg-brand-600 text-white" : "bg-[#1a1a2e] text-surface-500 hover:text-white"
            }`}
          >
            {t === "generate" ? "Generate Code" : t === "explain" ? "Explain Code" : "New Project"}
          </button>
        ))}
      </div>

      {tab === "project" ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {templates.map((t) => (
            <div key={t.id} className="glass rounded-xl p-5 card-hover cursor-pointer">
              <h3 className="text-lg font-semibold text-white mb-1">{t.name}</h3>
              <p className="text-sm text-surface-500 mb-3">{t.stack}</p>
              <button className="w-full py-2 rounded-lg bg-brand-600/20 text-brand-400 text-sm hover:bg-brand-600/30 transition">
                Create Project
              </button>
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input */}
          <div className="space-y-4">
            <div className="glass rounded-xl p-5">
              <div className="flex items-center justify-between mb-2">
                <label className="text-sm font-medium text-surface-400">
                  {tab === "generate" ? "What code do you need?" : "Paste code to explain"}
                </label>
                <select
                  value={language}
                  onChange={(e) => setLanguage(e.target.value)}
                  className="bg-[#12121a] border border-[#2a2a4a] rounded-lg px-3 py-1.5 text-white text-xs"
                >
                  {languages.map((l) => (
                    <option key={l} value={l}>{l}</option>
                  ))}
                </select>
              </div>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder={
                  tab === "generate"
                    ? "Build a REST API with CRUD operations for a todo app..."
                    : "Paste your code here to get an explanation..."
                }
                className="w-full h-48 bg-[#12121a] border border-[#2a2a4a] rounded-lg p-4 text-white font-mono text-sm placeholder:text-surface-600 resize-none focus:outline-none focus:border-brand-500"
              />
            </div>

            <button
              onClick={handleGenerate}
              disabled={!prompt.trim() || loading}
              className="w-full py-3 rounded-lg bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white font-semibold disabled:opacity-50 transition"
            >
              {loading ? "⏳ Generating..." : tab === "generate" ? "💻 Generate Code — 2 Credits" : "📖 Explain Code — 1 Credit"}
            </button>
          </div>

          {/* Output */}
          <div className="glass rounded-xl p-5">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-surface-300">
                {result ? "Generated Code" : "Output"}
              </h3>
              {result && (
                <button
                  onClick={() => navigator.clipboard.writeText(result)}
                  className="text-xs text-brand-400 hover:text-brand-300"
                >
                  📋 Copy
                </button>
              )}
            </div>
            <pre className="h-[400px] bg-[#0a0a0f] rounded-lg p-4 overflow-auto text-sm font-mono">
              <code className="text-green-400">
                {result || "// Your generated code will appear here..."}
              </code>
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
