"use client";
import { useState } from "react";

const contentTypes = [
  { id: "blog_post", name: "Blog Post", icon: "📝", desc: "Long-form articles" },
  { id: "ad_copy", name: "Ad Copy", icon: "📢", desc: "Marketing ads" },
  { id: "social_post", name: "Social Post", icon: "📱", desc: "Social media" },
  { id: "email", name: "Email", icon: "✉️", desc: "Email campaigns" },
  { id: "script", name: "Script", icon: "🎬", desc: "Video scripts" },
  { id: "product_desc", name: "Product", icon: "🛍️", desc: "Product copy" },
  { id: "press_release", name: "Press Release", icon: "📰", desc: "PR content" },
  { id: "landing_page", name: "Landing Page", icon: "🌐", desc: "Web copy" },
  { id: "seo_meta", name: "SEO Meta", icon: "🔍", desc: "SEO content" },
  { id: "resume", name: "Resume", icon: "📄", desc: "Professional CV" },
];

const tones = ["professional", "casual", "friendly", "authoritative", "humorous", "inspirational", "technical", "persuasive"];

export default function WriterPage() {
  const [contentType, setContentType] = useState("blog_post");
  const [topic, setTopic] = useState("");
  const [keywords, setKeywords] = useState("");
  const [tone, setTone] = useState("professional");
  const [wordCount, setWordCount] = useState(500);
  const [tab, setTab] = useState<"write" | "rewrite" | "seo">("write");
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    await new Promise((r) => setTimeout(r, 2000));
    const selected = contentTypes.find((c) => c.id === contentType)!;
    setResult(
      `# ${topic || "Your Amazing Topic"}\n\n` +
      `*Generated as ${selected.name} — ${tone} tone*\n\n` +
      `## Introduction\n\n` +
      `In today's rapidly evolving digital landscape, ${topic || "this subject"} has become increasingly important. ` +
      `This ${selected.name.toLowerCase()} explores the key aspects and provides actionable insights.\n\n` +
      `## Key Points\n\n` +
      `### 1. Understanding the Fundamentals\n\n` +
      `The foundation of ${topic || "this topic"} lies in understanding its core principles. ` +
      `By examining the data and trends, we can identify patterns that inform better decision-making.\n\n` +
      `### 2. Best Practices\n\n` +
      `Industry leaders recommend several approaches:\n\n` +
      `- **Data-Driven Decision Making**: Use analytics to guide strategy\n` +
      `- **Continuous Iteration**: Regularly review and optimize processes\n` +
      `- **User-Centric Design**: Always prioritize the end-user experience\n` +
      `- **Scalable Architecture**: Build systems that grow with demand\n\n` +
      `### 3. Future Outlook\n\n` +
      `As we look ahead, the evolution of ${topic || "this field"} promises exciting developments. ` +
      `Organizations that adapt early will gain significant competitive advantages.\n\n` +
      `## Conclusion\n\n` +
      `${topic || "This topic"} represents a transformative opportunity. ` +
      `By implementing the strategies outlined above, you can position yourself for success in this dynamic environment.\n\n` +
      `---\n*Generated by Ominou Studio AI Writer • ~${wordCount} words • Keywords: ${keywords || "AI, technology, innovation"}*`
    );
    setLoading(false);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 fade-in">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-3">✍️ AI Writer</h1>
        <p className="text-surface-500 mt-1">Generate professional content, blog posts, ad copy, and more</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2">
        {(["write", "rewrite", "seo"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
              tab === t ? "bg-brand-600 text-white" : "bg-[#1a1a2e] text-surface-500 hover:text-white"
            }`}
          >
            {t === "write" ? "✍️ Write" : t === "rewrite" ? "🔄 Rewrite" : "🔍 SEO Tools"}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Controls */}
        <div className="lg:col-span-1 space-y-4">
          {/* Content Type */}
          <div className="glass rounded-xl p-4">
            <label className="text-sm font-medium text-surface-400 mb-2 block">Content Type</label>
            <div className="grid grid-cols-2 gap-2 max-h-[220px] overflow-y-auto pr-1">
              {contentTypes.map((ct) => (
                <button
                  key={ct.id}
                  onClick={() => setContentType(ct.id)}
                  className={`p-2 rounded-lg text-left text-xs transition ${
                    contentType === ct.id
                      ? "bg-brand-600/20 border border-brand-500/50 text-white"
                      : "bg-[#12121a] text-surface-400 hover:text-white"
                  }`}
                >
                  <span>{ct.icon}</span> {ct.name}
                </button>
              ))}
            </div>
          </div>

          {/* Topic & Keywords */}
          <div className="glass rounded-xl p-4 space-y-3">
            <div>
              <label className="text-xs text-surface-400">Topic / Title</label>
              <input
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="The Future of AI in Healthcare"
                className="w-full mt-1 bg-[#12121a] border border-[#2a2a4a] rounded-lg px-3 py-2 text-white text-sm placeholder:text-surface-600 focus:outline-none focus:border-brand-500"
              />
            </div>
            <div>
              <label className="text-xs text-surface-400">Keywords</label>
              <input
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
                placeholder="AI, healthcare, machine learning"
                className="w-full mt-1 bg-[#12121a] border border-[#2a2a4a] rounded-lg px-3 py-2 text-white text-sm placeholder:text-surface-600 focus:outline-none focus:border-brand-500"
              />
            </div>
          </div>

          {/* Tone & Length */}
          <div className="glass rounded-xl p-4 space-y-3">
            <div>
              <label className="text-xs text-surface-400">Tone</label>
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                className="w-full mt-1 bg-[#12121a] border border-[#2a2a4a] rounded-lg px-3 py-2 text-white text-sm"
              >
                {tones.map((t) => (
                  <option key={t} value={t}>{t.charAt(0).toUpperCase() + t.slice(1)}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="text-xs text-surface-400">Word count: ~{wordCount}</label>
              <input
                type="range"
                min={100}
                max={3000}
                step={100}
                value={wordCount}
                onChange={(e) => setWordCount(Number(e.target.value))}
                className="w-full mt-1 accent-brand-500"
              />
              <div className="flex justify-between text-xs text-surface-600">
                <span>100</span>
                <span>3000</span>
              </div>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading}
            className="w-full py-3 rounded-lg bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white font-semibold disabled:opacity-50 transition"
          >
            {loading ? "⏳ Writing..." : "✍️ Generate Content — 2 Credits"}
          </button>
        </div>

        {/* Output */}
        <div className="lg:col-span-2">
          <div className="glass rounded-xl p-5 h-full">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-surface-300">
                {result ? "Generated Content" : "Output"}
              </h3>
              {result && (
                <div className="flex gap-2">
                  <button onClick={() => navigator.clipboard.writeText(result)} className="text-xs text-brand-400 hover:text-brand-300">📋 Copy</button>
                  <button className="text-xs text-surface-400 hover:text-white">💾 Save</button>
                </div>
              )}
            </div>
            <div className="h-[500px] bg-[#0a0a0f] rounded-lg p-5 overflow-auto prose prose-invert prose-sm max-w-none">
              {result ? (
                <div className="whitespace-pre-wrap text-surface-300 text-sm leading-relaxed">{result}</div>
              ) : (
                <div className="h-full flex items-center justify-center text-surface-500">
                  <div className="text-center">
                    <p className="text-4xl mb-3">✍️</p>
                    <p className="text-sm">Your generated content will appear here</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
